# Generated by Django 6.1.1 on 2026-09-08 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de Catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du Produit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (DH)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantité en Stock')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.category', verbose_name='Catégorie')),
            ],
        ),
    ]
